//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConservation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConservationEntities : DbContext
    {
        public ConservationEntities()
            : base("name=ConservationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrateur> Administrateurs { get; set; }
        public DbSet<Diplome> Diplomes { get; set; }
        public DbSet<DocumentPublier> DocumentPubliers { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<DomaineFormation> DomaineFormations { get; set; }
        public DbSet<Etudiant> Etudiants { get; set; }
        public DbSet<Evenement> Evenements { get; set; }
        public DbSet<Galery> Galeries { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<NatureDocument> NatureDocuments { get; set; }
        public DbSet<Universite> Universites { get; set; }
    }
}
