//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConservation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    
    
    public partial class Document
    {
        public Document()
        {
            this.DocumentPubliers = new HashSet<DocumentPublier>();
        }
    
        public int id { get; set; }
        public string titre { get; set; }
        public int nomAuteur { get; set; }
        public int universite { get; set; }
        public int diplome { get; set; }
        public int domaine { get; set; }
        public int nature { get; set; }
        public int annee { get; set; }
        public string FileName { get; set; }
        public HttpPostedFileBase FileUploadFile { get; set; }
        [DataType(DataType.Upload)]
        [Display(Name = "Upload File")]
        [Required(ErrorMessage = "Please choose file to upload.")]
         
        public string fichier { get; set; }
        
       // [NotMapped]
        [DisplayName("upload file")]
        public HttpPostedFileBase docfile { get; set; }

        public bool etatPublication { get; set; }
        public bool autoriseTelecharge { get; set; }
    
        public virtual Diplome Diplome1 { get; set; }
        public virtual ICollection<DocumentPublier> DocumentPubliers { get; set; }
        public virtual DomaineFormation DomaineFormation { get; set; }
        public virtual NatureDocument NatureDocument { get; set; }
        public virtual Etudiant Etudiant { get; set; }
        public virtual Universite Universite1 { get; set; }
    }
}
